### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KSKOP69** [Pranav-Saraswat/Testing-Alpha#13]
```
[12-Nov-23 15:51:41 - ERROR] - pyrogram.dispatcher - 'ChannelForbidden' object has no attribute 'chat_id'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/usr/local/lib/python3.10/dist-packages/pytgcalls/mtproto/pyrogram_client.py", line 98, in on_update
    chat_id = self.chat_id(data2[update.chat_id])
  File "/usr/local/lib/python3.10/dist-packages/pytgcalls/mtproto/bridged_client.py", line 98, in chat_id
    return -input_peer.chat_id
AttributeError: 'ChannelForbidden' object has no attribute 'chat_id'
```

**Comment by Pranav-Saraswat** [comment]
@KSKOP69 when you face any error just type the everthing that How you face the error what you are trying to do?

**Comment by KSKOP69** [comment]
i was this repo and got this error

**Comment by Pranav-Saraswat** [comment]
what do you mean ?

I said just send a reproduce error and where you have been face this issue

**Comment by KSKOP69** [comment]
[13-Nov-23 17:35:22 - ERROR] - asyncio - Task exception was never retrieved
future: <Task finished name='Task-3333990' coro=<Start.start.<locals>.participants_handler() done, defined at /usr/local/lib/python3.10/dist-packages/pytgcalls/methods/utilities/start.py:19> exception=ConnectionNotFound('Connection with chat id "-1001692328939" not found')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pytgcalls/methods/utilities/start.py", line 34, in participants_handler
    self._binding.get_state(chat_id),
ntgcalls.ConnectionNotFound: Connection with chat id "-1001692328939" not found
[13-Nov-23 17:36:12 - ERROR] - asyncio - Task exception was never retrieved
future: <Task finished name='Task-3336815' coro=<Start.start.<locals>.participants_handler() done, defined at /usr/local/lib/python3.10/dist-packages/pytgcalls/methods/utilities/start.py:19> exception=ConnectionNotFound('Connection with chat id "-1001692328939" not found')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pytgcalls/methods/utilities/start.py", line 34, in participants_handler
    self._binding.get_state(chat_id),
ntgcalls.ConnectionNotFound: Connection with chat id "-1001692328939" not found
[13-Nov-23 17:36:32 - ERROR] - asyncio - Task exception was never retrieved
future: <Task finished name='Task-3337934' coro=<Start.start.<locals>.participants_handler() done, defined at /usr/local/lib/python3.10/dist-packages/pytgcalls/methods/utilities/start.py:19> exception=ConnectionNotFound('Connection with chat id "-1001692328939" not found')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pytgcalls/methods/utilities/start.py", line 34, in participants_handler
    self._binding.get_state(chat_id),
ntgcalls.ConnectionNotFound: Connection with chat id "-1001692328939" not found
[13-Nov-23 17:43:21 - ERROR] - asyncio - Task exception was never retrieved
future: <Task finished name='Task-3359477' coro=<Start.start.<locals>.participants_handler() done, defined at /usr/local/lib/python3.10/dist-packages/pytgcalls/methods/utilities/start.py:19> exception=ConnectionNotFound('Connection with chat id "-1001925252783" not found')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pytgcalls/methods/utilities/start.py", line 34, in participants_handler
    self._binding.get_state(chat_id),
ntgcalls.ConnectionNotFound: Connection with chat id "-1001925252783" not found
``

**Comment by KSKOP69** [comment]
```
[13-Nov-23 17:35:22 - ERROR] - asyncio - Task exception was never retrieved
future: <Task finished name='Task-3333990' coro=<Start.start..participants_handler() done, defined at /usr/local/lib/python3.10/dist-packages/pytgcalls/methods/utilities/start.py:19> exception=ConnectionNotFound('Connection with chat id "-1001692328939" not found')>
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/pytgcalls/methods/utilities/start.py", line 34, in participants_handler
self._binding.get_state(chat_id),
ntgcalls.ConnectionNotFound: Connection with chat id "-1001692328939" not found
[13-Nov-23 17:36:12 - ERROR] - asyncio - Task exception was never retrieved
future: <Task finished name='Task-3336815' coro=<Start.start..participants_handler() done, defined at /usr/local/lib/python3.10/dist-packages/pytgcalls/methods/utilities/start.py:19> exception=ConnectionNotFound('Connection with chat id "-1001692328939" not found')>
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/pytgcalls/methods/utilities/start.py", line 34, in participants_handler
self._binding.get_state(chat_id),
ntgcalls.ConnectionNotFound: Connection with chat id "-1001692328939" not found
[13-Nov-23 17:36:32 - ERROR] - asyncio - Task exception was never retrieved
future: <Task finished name='Task-3337934' coro=<Start.start..participants_handler() done, defined at /usr/local/lib/python3.10/dist-packages/pytgcalls/methods/utilities/start.py:19> exception=ConnectionNotFound('Connection with chat id "-1001692328939" not found')>
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/pytgcalls/methods/utilities/start.py", line 34, in participants_handler
self._binding.get_state(chat_id),
ntgcalls.ConnectionNotFound: Connection with chat id "-1001692328939" not found
[13-Nov-23 17:43:21 - ERROR] - asyncio - Task exception was never retrieved
future: <Task finished name='Task-3359477' coro=<Start.start..participants_handler() done, defined at /usr/local/lib/python3.10/dist-packages/pytgcalls/methods/utilities/start.py:19> exception=ConnectionNotFound('Connection with chat id "-1001925252783" not found')>
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/pytgcalls/methods/utilities/start.py", line 34, in participants_handler
self._binding.get_state(chat_id),
ntgcalls.ConnectionNotFound: Connection with chat id "-1001925252783" not found
```

**Comment by KSKOP69** [comment]
```
pyrogram.errors.exceptions.bad_request_400.TopicClosed: Telegram says: [400 TOPIC_CLOSED] - This topic was closed, you can't send messages to it anymore (caused by "messages.SendMessage")
[13-Nov-23 00:00:47 - ERROR] - pyrogram.dispatcher - Telegram says: [400 TOPIC_CLOSED] - This topic was closed, you can't send messages to it anymore (caused by "messages.SendMessage")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/KSKOP/YukkiMusic/utils/decorators/language.py", line 56, in wrapper
    return await mystic(_, message, language)
  File "/root/KSKOP/YukkiMusic/plugins/bot/start.py", line 231, in testbot
    return await message.reply_text(
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/types/messages_and_media/message.py", line 992, in reply_text
    return await self._client.send_message(
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/messages/send_message.py", line 137, in send_message
    r = await self.invoke(
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.TopicClosed: Telegram says: [400 TOPIC_CLOSED] - This topic was closed, you can't send messages to it anymore (caused by "messages.SendMessage")
[13-Nov-23 00:00:49 - ERROR] - pyrogram.dispatcher - Telegram says: [400 TOPIC_CLOSED] - This topic was closed, you can't send messages to it anymore (caused by "messages.SendMessage")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/KSKOP/YukkiMusic/utils/decorators/language.py", line 56, in wrapper
    return await mystic(_, message, language)
  File "/root/KSKOP/YukkiMusic/plugins/bot/start.py", line 231, in testbot
    return await message.reply_text(
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/types/messages_and_media/message.py", line 992, in reply_text
    return await self._client.send_message(
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/messages/send_message.py", line 137, in send_message
    r = await self.invoke(
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.TopicClosed: Telegram says: [400 TOPIC_CLOSED] - This topic was closed, you can't send messages to it anymore (caused by "messages.SendMessage")
[13-Nov-23 00:01:05 - ERROR] - pyrogram.dispatcher - Telegram says: [400 TOPIC_CLOSED] - This topic was closed, you can't send messages to it anymore (caused by "messages.SendMedia")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/KSKOP/YukkiMusic/utils/decorators/play.py", line 72, in wrapper
    return await message.reply_photo(
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/types/messages_and_media/message.py", line 2076, in reply_photo
    return await self._client.send_photo(
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/messages/send_photo.py", line 188, in send_photo
    r = await self.invoke(
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.TopicClosed: Telegram says: [400 TOPIC_CLOSED] - This topic was closed, you can't send messages to it anymore (caused by "messages.SendMedia")
```

**Comment by Pranav-Saraswat** [comment]
@annihilatorrrr Buddy Can you checkout this If you can?

**Comment by Pranav-Saraswat** [comment]
@KSKOP69 still its half reproduce error can you send all whole error you have?

**Comment by annihilatorrrr** [comment]
can be a pytgcalls bug

**Comment by Pranav-Saraswat** [comment]
@annihilatorrrr fine I'll send this is to laky for this have you face this issue btw?

**Comment by annihilatorrrr** [comment]
> @annihilatorrrr fine I'll send this is to laky for this have you face this issue btw?

nopes

**Comment by KSKOP69** [comment]
```
[14-Nov-23 07:35:36 - ERROR] - pyrogram.dispatcher - 'vidid'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/KSKOP/YukkiMusic/utils/decorators/language.py", line 44, in wrapper
    return await mystic(_, CallbackQuery, language)
  File "/root/KSKOP/YukkiMusic/plugins/play/toptracks.py", line 78, in server_to_play
    stats = await get_global_tops()
  File "/root/KSKOP/YukkiMusic/utils/database/mongodatabase.py", line 293, in get_global_tops
    for i in chat["vidid"]:
KeyError: 'vidid'
[14-Nov-23 07:35:51 - ERROR] - pyrogram.dispatcher - 'vidid'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/KSKOP/YukkiMusic/utils/decorators/language.py", line 26, in wrapper
    return await mystic(_, message, language)
  File "/root/KSKOP/YukkiMusic/plugins/tools/stats.py", line 65, in gstats_global
    stats = await get_global_tops()
  File "/root/KSKOP/YukkiMusic/utils/database/mongodatabase.py", line 293, in get_global_tops
    for i in chat["vidid"]:
KeyError: 'vidid'
[14-Nov-23 15:47:33 - ERROR] - pyrogram.dispatcher - argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/KSKOP/YukkiMusic/utils/decorators/play.py", line 117, in wrapper
    if "-v" in message.text:
TypeError: argument of type 'NoneType' is not iterable
[14-Nov-23 15:57:33 - ERROR] - pyrogram.dispatcher - argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/KSKOP/YukkiMusic/utils/decorators/play.py", line 117, in wrapper
    if "-v" in message.text:
TypeError: argument of type 'NoneType' is not iterable
[14-Nov-23 17:08:22 - ERROR] - pyrogram.dispatcher - Telegram says: [406 CHANNEL_PRIVATE] - The channel/supergroup is not accessible (caused by "channels.GetMessages")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 214, in handler_worker
    await parser(update, users, chats)
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 68, in message_parser
    await pyrogram.types.Message._parse(self.client, update.message, users, chats,
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/types/messages_and_media/message.py", line 853, in _parse
    reply_to_message = await client.get_messages(
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/messages/get_messages.py", line 115, in get_messages
    r = await self.invoke(rpc, sleep_threshold=-1)
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.not_acceptable_406.ChannelPrivate: Telegram says: [406 CHANNEL_PRIVATE] - The channel/supergroup is not accessible (caused by "channels.GetMessages")

```

**Comment by annihilatorrrr** [comment]
looks like u are using the old version of this repo, please git pull and see.

**Comment by KSKOP69** [comment]
[Heroku Error](https://pasty.lus.pm/nue0kI#c6e4ca6deb57ea3429afab10739d45b64f8682af50d9520b979ab31ccc145458)
