### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KSKOP69** [Pranav-Saraswat/Testing-Alpha#16]
```
[15-Nov-23 23:01:43 - ERROR] - pyrogram.dispatcher - Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You can't write in this chat (caused by "messages.SendMessage")
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/app/YukkiMusic/utils/decorators/admins.py", line 61, in wrapper
    return await message.reply_text(_["general_6"])
  File "/opt/venv/lib/python3.10/site-packages/pyrogram/types/messages_and_media/message.py", line 1003, in reply_text
    return await self._client.send_message(
  File "/opt/venv/lib/python3.10/site-packages/pyrogram/methods/messages/send_message.py", line 137, in send_message
    r = await self.invoke(
  File "/opt/venv/lib/python3.10/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/opt/venv/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.forbidden_403.ChatWriteForbidden: Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You can't write in this chat (caused by "messages.SendMessage")
```

**Comment by KSKOP69** [comment]
```
[21-Nov-23 20:23:35 - ERROR] - pyrogram.dispatcher - Telegram says: [420 FLOOD_WAIT_X] - A wait of 13 seconds is required (caused by "messages.SendMessage")
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/app/YukkiMusic/utils/decorators/language.py", line 26, in wrapper
    return await mystic(_, message, language)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/YukkiMusic/plugins/play/playmode.py", line 30, in playmode_
    response = await message.reply_text(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pyrogram/types/messages_and_media/message.py", line 1003, in reply_text
    return await self._client.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pyrogram/methods/messages/send_message.py", line 137, in send_message
    r = await self.invoke(
        ^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/opt/venv/lib/python3.11/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 13 seconds is required (caused by "messages.SendMessage")
```

**Comment by Pranav-Saraswat** [comment]
this is flood wait error that you face I'll change the whole code to telethon when I'll free till then just try to adjust with this please

**Comment by KSKOP69** [comment]
```
[22-Nov-23 22:08:32 - ERROR] - pyrogram.dispatcher - 'list' object has no attribute 'write'
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/app/YukkiMusic/utils/decorators/language.py", line 44, in wrapper
    return await mystic(_, CallbackQuery, language)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/YukkiMusic/plugins/play/toptracks.py", line 84, in server_to_play
    return await mystic.edit(
           ^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pyrogram/types/messages_and_media/message.py", line 2927, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pyrogram/methods/messages/edit_message_text.py", line 87, in edit_message_text
    reply_markup=await reply_markup.write(self) if reply_markup else None,
                       ^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'write'



[22-Nov-23 20:39:46 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/app/YukkiMusic/utils/decorators/play.py", line 115, in wrapper
    return await command(
           ^^^^^^^^^^^^^^
  File "/app/YukkiMusic/plugins/play/play.py", line 402, in play_commnd
    query = message.text.split(None, 1)[1]
            ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by KSKOP69** [comment]
```
[25-Nov-23 18:34:51 - ERROR] - pyrogram.dispatcher - 'ChannelForbidden' object has no attribute 'chat_id'
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/opt/venv/lib/python3.11/site-packages/pytgcalls/mtproto/pyrogram_client.py", line 98, in on_update
    chat_id = self.chat_id(data2[update.chat_id])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pytgcalls/mtproto/bridged_client.py", line 98, in chat_id
    return -input_peer.chat_id
            ^^^^^^^^^^^^^^^^^^
AttributeError: 'ChannelForbidden' object has no attribute 'chat_id'
```

**Comment by KSKOP69** [comment]
> ```
> [25-Nov-23 18:34:51 - ERROR] - pyrogram.dispatcher - 'ChannelForbidden' object has no attribute 'chat_id'
> Traceback (most recent call last):
>   File "/opt/venv/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
>     await handler.callback(self.client, *args)
>   File "/opt/venv/lib/python3.11/site-packages/pytgcalls/mtproto/pyrogram_client.py", line 98, in on_update
>     chat_id = self.chat_id(data2[update.chat_id])
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/venv/lib/python3.11/site-packages/pytgcalls/mtproto/bridged_client.py", line 98, in chat_id
>     return -input_peer.chat_id
>             ^^^^^^^^^^^^^^^^^^
> AttributeError: 'ChannelForbidden' object has no attribute 'chat_id'
> ```
This error is fixed

**Comment by AnonymousX1025** [comment]
> this is flood wait error that you face I'll change the whole code to telethon when I'll free till then just try to adjust with this please

You'll change the library because of floodwait ? 🤡

**Comment by Pranav-Saraswat** [comment]
> > this is flood wait error that you face I'll change the whole code to telethon when I'll free till then just try to adjust with this please
> 
> You'll change the library because of floodwait ? 🤡

nope but I want to change because of telegram updates that pyro doesnt have

**Comment by elishabolles85** [comment]
هناك مشكلة في مكتبه يوتيوب هل سوف تقوم بعمل نظام بروكسي

> > > هذا خطأ في الانتظار الذي تواجهه، سأغير الرمز بالكامل إلى telethon عندما أكون حرًا حتى ذلك الحين، فقط حاول التكيف مع هذا من فضلك
> > 
> > 
> > هل ستقوم بتغيير المكتبة بسبب الانتظار الفيضان؟ 🤡
> 
> لا ولكني أريد التغيير بسبب تحديثات التليجرام التي لا يتوفر بها pyro

**Comment by elishabolles85** [comment]
> > > هذا خطأ في الانتظار الذي تواجهه، سأغير الرمز بالكامل إلى telethon عندما أكون حرًا حتى ذلك الحين، فقط حاول التكيف مع هذا من فضلك
> > 
> > 
> > هل ستقوم بتغيير المكتبة بسبب الانتظار الفيضان؟ 🤡
> 
> لا ولكني أريد التغيير بسبب تحديثات التليجرام التي لا يتوفر بها pyro

هناك مشكلة في مكتبه يوتيوب هل سوف تقوم بعمل نظام بروكسي

**Comment by AnonymousX1025** [comment]
> > > this is flood wait error that you face I'll change the whole code to telethon when I'll free till then just try to adjust with this please
> > 
> > 
> > You'll change the library because of floodwait ? 🤡
> 
> nope but I want to change because of telegram updates that pyro doesnt have

Update pyro then ?

**Comment by KSKOP69** [comment]
```
2023-12-01T17:58:36.803441+00:00 app[worker.1]: [01-Dec-23 23:28:36 - ERROR] - pyrogram.methods.advanced.save_file - [Errno 32] Broken pipe
2023-12-01T17:58:36.803442+00:00 app[worker.1]: Traceback (most recent call last):
2023-12-01T17:58:36.803442+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/methods/advanced/save_file.py", line 109, in worker
2023-12-01T17:58:36.803443+00:00 app[worker.1]:     await session.invoke(data)
2023-12-01T17:58:36.803443+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 412, in invoke
2023-12-01T17:58:36.803445+00:00 app[worker.1]:     return await self.invoke(query, retries - 1, timeout)
2023-12-01T17:58:36.803445+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 412, in invoke
2023-12-01T17:58:36.803445+00:00 app[worker.1]:     return await self.invoke(query, retries - 1, timeout)
2023-12-01T17:58:36.803445+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 412, in invoke
2023-12-01T17:58:36.803446+00:00 app[worker.1]:     return await self.invoke(query, retries - 1, timeout)
2023-12-01T17:58:36.803446+00:00 app[worker.1]:   [Previous line repeated 7 more times]
2023-12-01T17:58:36.803446+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 402, in invoke
2023-12-01T17:58:36.803446+00:00 app[worker.1]:     raise e from None
2023-12-01T17:58:36.803447+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 389, in invoke
2023-12-01T17:58:36.803447+00:00 app[worker.1]:     return await self.send(query, timeout=timeout)
2023-12-01T17:58:36.803447+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 340, in send
2023-12-01T17:58:36.803447+00:00 app[worker.1]:     raise e
2023-12-01T17:58:36.803448+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 337, in send
2023-12-01T17:58:36.803448+00:00 app[worker.1]:     await self.connection.send(payload)
2023-12-01T17:58:36.803448+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/connection/connection.py", line 69, in send
2023-12-01T17:58:36.803448+00:00 app[worker.1]:     await self.protocol.send(data)
2023-12-01T17:58:36.803449+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/connection/transport/tcp/tcp_abridged.py", line 38, in send
2023-12-01T17:58:36.803449+00:00 app[worker.1]:     await super().send(
2023-12-01T17:58:36.803449+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/connection/transport/tcp/tcp.py", line 104, in send
2023-12-01T17:58:36.803449+00:00 app[worker.1]:     raise OSError(e)
2023-12-01T17:58:36.803449+00:00 app[worker.1]: OSError: [Errno 32] Broken pipe
```

**Comment by AnonymousX1025** [comment]
> ```
> 2023-12-01T17:58:36.803441+00:00 app[worker.1]: [01-Dec-23 23:28:36 - ERROR] - pyrogram.methods.advanced.save_file - [Errno 32] Broken pipe
> 2023-12-01T17:58:36.803442+00:00 app[worker.1]: Traceback (most recent call last):
> 2023-12-01T17:58:36.803442+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/methods/advanced/save_file.py", line 109, in worker
> 2023-12-01T17:58:36.803443+00:00 app[worker.1]:     await session.invoke(data)
> 2023-12-01T17:58:36.803443+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 412, in invoke
> 2023-12-01T17:58:36.803445+00:00 app[worker.1]:     return await self.invoke(query, retries - 1, timeout)
> 2023-12-01T17:58:36.803445+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 412, in invoke
> 2023-12-01T17:58:36.803445+00:00 app[worker.1]:     return await self.invoke(query, retries - 1, timeout)
> 2023-12-01T17:58:36.803445+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 412, in invoke
> 2023-12-01T17:58:36.803446+00:00 app[worker.1]:     return await self.invoke(query, retries - 1, timeout)
> 2023-12-01T17:58:36.803446+00:00 app[worker.1]:   [Previous line repeated 7 more times]
> 2023-12-01T17:58:36.803446+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 402, in invoke
> 2023-12-01T17:58:36.803446+00:00 app[worker.1]:     raise e from None
> 2023-12-01T17:58:36.803447+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 389, in invoke
> 2023-12-01T17:58:36.803447+00:00 app[worker.1]:     return await self.send(query, timeout=timeout)
> 2023-12-01T17:58:36.803447+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 340, in send
> 2023-12-01T17:58:36.803447+00:00 app[worker.1]:     raise e
> 2023-12-01T17:58:36.803448+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 337, in send
> 2023-12-01T17:58:36.803448+00:00 app[worker.1]:     await self.connection.send(payload)
> 2023-12-01T17:58:36.803448+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/connection/connection.py", line 69, in send
> 2023-12-01T17:58:36.803448+00:00 app[worker.1]:     await self.protocol.send(data)
> 2023-12-01T17:58:36.803449+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/connection/transport/tcp/tcp_abridged.py", line 38, in send
> 2023-12-01T17:58:36.803449+00:00 app[worker.1]:     await super().send(
> 2023-12-01T17:58:36.803449+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/connection/transport/tcp/tcp.py", line 104, in send
> 2023-12-01T17:58:36.803449+00:00 app[worker.1]:     raise OSError(e)
> 2023-12-01T17:58:36.803449+00:00 app[worker.1]: OSError: [Errno 32] Broken pipe
> ```

Connection errors 🤡

**Comment by Pranav-Saraswat** [comment]
change it to hydrogram

**Comment by KSKOP69** [comment]
> > ```
> > 2023-12-01T17:58:36.803441+00:00 app[worker.1]: [01-Dec-23 23:28:36 - ERROR] - pyrogram.methods.advanced.save_file - [Errno 32] Broken pipe
> > 2023-12-01T17:58:36.803442+00:00 app[worker.1]: Traceback (most recent call last):
> > 2023-12-01T17:58:36.803442+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/methods/advanced/save_file.py", line 109, in worker
> > 2023-12-01T17:58:36.803443+00:00 app[worker.1]:     await session.invoke(data)
> > 2023-12-01T17:58:36.803443+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 412, in invoke
> > 2023-12-01T17:58:36.803445+00:00 app[worker.1]:     return await self.invoke(query, retries - 1, timeout)
> > 2023-12-01T17:58:36.803445+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 412, in invoke
> > 2023-12-01T17:58:36.803445+00:00 app[worker.1]:     return await self.invoke(query, retries - 1, timeout)
> > 2023-12-01T17:58:36.803445+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 412, in invoke
> > 2023-12-01T17:58:36.803446+00:00 app[worker.1]:     return await self.invoke(query, retries - 1, timeout)
> > 2023-12-01T17:58:36.803446+00:00 app[worker.1]:   [Previous line repeated 7 more times]
> > 2023-12-01T17:58:36.803446+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 402, in invoke
> > 2023-12-01T17:58:36.803446+00:00 app[worker.1]:     raise e from None
> > 2023-12-01T17:58:36.803447+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 389, in invoke
> > 2023-12-01T17:58:36.803447+00:00 app[worker.1]:     return await self.send(query, timeout=timeout)
> > 2023-12-01T17:58:36.803447+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 340, in send
> > 2023-12-01T17:58:36.803447+00:00 app[worker.1]:     raise e
> > 2023-12-01T17:58:36.803448+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 337, in send
> > 2023-12-01T17:58:36.803448+00:00 app[worker.1]:     await self.connection.send(payload)
> > 2023-12-01T17:58:36.803448+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/connection/connection.py", line 69, in send
> > 2023-12-01T17:58:36.803448+00:00 app[worker.1]:     await self.protocol.send(data)
> > 2023-12-01T17:58:36.803449+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/connection/transport/tcp/tcp_abridged.py", line 38, in send
> > 2023-12-01T17:58:36.803449+00:00 app[worker.1]:     await super().send(
> > 2023-12-01T17:58:36.803449+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/connection/transport/tcp/tcp.py", line 104, in send
> > 2023-12-01T17:58:36.803449+00:00 app[worker.1]:     raise OSError(e)
> > 2023-12-01T17:58:36.803449+00:00 app[worker.1]: OSError: [Errno 32] Broken pipe
> > ```
> 
> Connection errors 🤡

but no one asked

**Comment by AnonymousX1025** [comment]
> > > ```
> > > 2023-12-01T17:58:36.803441+00:00 app[worker.1]: [01-Dec-23 23:28:36 - ERROR] - pyrogram.methods.advanced.save_file - [Errno 32] Broken pipe
> > > 2023-12-01T17:58:36.803442+00:00 app[worker.1]: Traceback (most recent call last):
> > > 2023-12-01T17:58:36.803442+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/methods/advanced/save_file.py", line 109, in worker
> > > 2023-12-01T17:58:36.803443+00:00 app[worker.1]:     await session.invoke(data)
> > > 2023-12-01T17:58:36.803443+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 412, in invoke
> > > 2023-12-01T17:58:36.803445+00:00 app[worker.1]:     return await self.invoke(query, retries - 1, timeout)
> > > 2023-12-01T17:58:36.803445+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 412, in invoke
> > > 2023-12-01T17:58:36.803445+00:00 app[worker.1]:     return await self.invoke(query, retries - 1, timeout)
> > > 2023-12-01T17:58:36.803445+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 412, in invoke
> > > 2023-12-01T17:58:36.803446+00:00 app[worker.1]:     return await self.invoke(query, retries - 1, timeout)
> > > 2023-12-01T17:58:36.803446+00:00 app[worker.1]:   [Previous line repeated 7 more times]
> > > 2023-12-01T17:58:36.803446+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 402, in invoke
> > > 2023-12-01T17:58:36.803446+00:00 app[worker.1]:     raise e from None
> > > 2023-12-01T17:58:36.803447+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 389, in invoke
> > > 2023-12-01T17:58:36.803447+00:00 app[worker.1]:     return await self.send(query, timeout=timeout)
> > > 2023-12-01T17:58:36.803447+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 340, in send
> > > 2023-12-01T17:58:36.803447+00:00 app[worker.1]:     raise e
> > > 2023-12-01T17:58:36.803448+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 337, in send
> > > 2023-12-01T17:58:36.803448+00:00 app[worker.1]:     await self.connection.send(payload)
> > > 2023-12-01T17:58:36.803448+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/connection/connection.py", line 69, in send
> > > 2023-12-01T17:58:36.803448+00:00 app[worker.1]:     await self.protocol.send(data)
> > > 2023-12-01T17:58:36.803449+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/connection/transport/tcp/tcp_abridged.py", line 38, in send
> > > 2023-12-01T17:58:36.803449+00:00 app[worker.1]:     await super().send(
> > > 2023-12-01T17:58:36.803449+00:00 app[worker.1]:   File "/opt/venv/lib/python3.10/site-packages/pyrogram/connection/transport/tcp/tcp.py", line 104, in send
> > > 2023-12-01T17:58:36.803449+00:00 app[worker.1]:     raise OSError(e)
> > > 2023-12-01T17:58:36.803449+00:00 app[worker.1]: OSError: [Errno 32] Broken pipe
> > > ```
> > 
> > Connection errors 🤡
> 
> but no one asked from you.  🤡

Stfu

**Comment by ITZ-ZAID** [comment]
@AnonymousX1025 maybe your os issue try increasing your server specs.

**Comment by AnonymousX1025** [comment]
> @AnonymousX1025 maybe your os issue try increasing your server specs.

Blind or wot?

**Comment by ITZ-ZAID** [comment]
@AnonymousX1025 Bhai use hi kew kr rhe? Jab stable nhi??

**Comment by AnonymousX1025** [comment]
> @AnonymousX1025 Bhai use hi kew kr rhe? Jab stable nhi??

Bc chutiya hai kya ? Author dekh pehle koun hai issue ka

**Comment by ITZ-ZAID** [comment]
@AnonymousX1025 Before raising try Google https://www.google.com/search?q=OSError: [Errno 32] Broken pipe

**Comment by AnonymousX1025** [comment]
> @AnonymousX1025 Before raising try Google https://www.google.com/search?q=OSError: [Errno 32] Broken pipe

Sach main chutiya hai bc, pehle dekh toh le bkl issue ka author koun hai

**Comment by ITZ-ZAID** [comment]
@AnonymousX1025 Oh sorry, Author ksk h @GitHubBot se response kr rha

**Comment by AnonymousX1025** [comment]
> @AnonymousX1025 Oh sorry, Author ksk h @GitHubBot se response kr rha

🤡

**Comment by ITZ-ZAID** [comment]
@KSKOP69 Fork toh fork hi hota issues thodi change ho jate!

**Comment by ITZ-ZAID** [comment]
@KSKOP69 Bhai kuchh khas diffrence nhi h! Timepass hai

**Comment by KSKOP69** [comment]
> @KSKOP69 Bhai kuchh khas diffrence nhi h! Timepass hai

[Dekh](https://t.me/pytgcallschat/68597)
